/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Settings = IDL.Record({
  'vibrationEnabled' : IDL.Bool,
  'ndModeEnabled' : IDL.Bool,
  'audioVolume' : IDL.Nat,
  'vibrationStrength' : IDL.Nat,
  'audioEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Settings = IDL.Record({
    'vibrationEnabled' : IDL.Bool,
    'ndModeEnabled' : IDL.Bool,
    'audioVolume' : IDL.Nat,
    'vibrationStrength' : IDL.Nat,
    'audioEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };